<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DFEV0VQ" failures="2" tests="4" name="SquareRootTest" time="2.009" errors="0" timestamp="10 Jan 2021 07:05:35 GMT">
  <testcase classname="SquareRootTest" name="testNegative" time="1.002">
    <failure message="
Expected exception java.lang.ArithmeticException but got org.testng.TestException: 
Expected exception java.lang.ArithmeticException but got org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testNegative() didn&#039;t finish within the time-out 1000" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.ArithmeticException but got org.testng.TestException: 
Expected exception java.lang.ArithmeticException but got org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testNegative() didn't finish within the time-out 1000
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1459)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1222)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
Caused by: org.testng.TestException: 
Expected exception java.lang.ArithmeticException but got org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testNegative() didn't finish within the time-out 1000
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1459)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:740)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	... 25 more
Caused by: org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testNegative() didn't finish within the time-out 1000
	at app//Calculator.squareRoot(Calculator.java:33)
	at app//SquareRootTest.testNegative(SquareRootTest.java:21)
	at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@15.0.1/java.lang.reflect.Method.invoke(Method.java:564)
	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.base@15.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base@15.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base@15.0.1/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase>
  <testcase classname="SquareRootTest" name="testCase" time="0.001"/>
  <testcase classname="SquareRootTest" name="testCase" time="1.003">
    <failure message="Method org.testng.internal.TestNGMethod.testCase() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testCase() didn't finish within the time-out 1000
	at app//Calculator.squareRoot(Calculator.java:33)
	at app//SquareRootTest.testCase(SquareRootTest.java:8)
	at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@15.0.1/java.lang.reflect.Method.invoke(Method.java:564)
	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.base@15.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base@15.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base@15.0.1/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase>
  <testcase classname="SquareRootTest" name="testCase" time="0.003"/>
</testsuite>
